- name: Commit and push changes
  run: |
    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    git add .

    # Only commit and push if there are changes
    if ! git diff --staged --quiet; then
      git commit -m "Auto-sync agents from source repos"
      
      # Configure HTTPS push with DOC_SYNC PAT
      git remote set-url origin https://x-access-token:${{ secrets.DOC_SYNC }}@github.com/${{ github.repository }}.git
      git push origin main
      
      # Only trigger sync-docs if we actually committed changes
      echo "Triggering sync-docs workflow..."
      response=$(curl -s -w "\n%{http_code}" -X POST \
        -H "Authorization: Bearer ${{ secrets.DOC_SYNC }}" \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/dispatches \
        -d '{"event_type":"sync-docs","client_payload":{"repo_url":"git@github.com:${{ github.repository }}.git"}}')

      http_code=$(echo "$response" | tail -n1)
      response_body=$(echo "$response" | head -n -1)

      if [ "$http_code" = "204" ]; then
        echo "Dispatch event sent successfully to sync-docs"
      else
        echo "Failed to send dispatch event. Status: $http_code"
        echo "Response: $response_body"
        exit 1
      fi
    else
      echo "No changes to commit, skipping sync-docs trigger"
    fi
env:
  GITHUB_TOKEN: ${{ secrets.DOC_SYNC }}