name: Dispatch Docs Sync to GitBooks

on:
  push:
    branches: [main]
    paths:
      - "markdown/**"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync-docs in gitbooks-repo
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.DOC_SYNC }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/alert-d/gitbooks/dispatches \
            -d '{"event_type":"sync-docs"}')

          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | head -n -1)

          if [ "$http_code" = "204" ]; then
            echo "Dispatch event sent successfully"
          else
            echo "Failed to send dispatch event. Status: $http_code"
            echo "Response: $response_body"
            exit 1
          fi
